export interface CountryPrefix {
  code: string;
  name: string;
  prefix: string;
}

export const countryPrefixes: CountryPrefix[] = [
  { code: 'AL', name: 'Albania', prefix: '+355' },
  { code: 'AD', name: 'Andorra', prefix: '+376' },
  { code: 'AT', name: 'Austria', prefix: '+43' },
  { code: 'BY', name: 'Belarus', prefix: '+375' },
  { code: 'BE', name: 'Belgium', prefix: '+32' },
  { code: 'BA', name: 'Bosnia and Herzegovina', prefix: '+387' },
  { code: 'BG', name: 'Bulgaria', prefix: '+359' },
  { code: 'HR', name: 'Croatia', prefix: '+385' },
  { code: 'CZ', name: 'Czech Republic', prefix: '+420' },
  { code: 'DK', name: 'Denmark', prefix: '+45' },
  { code: 'EE', name: 'Estonia', prefix: '+372' },
  { code: 'FI', name: 'Finland', prefix: '+358' },
  { code: 'FR', name: 'France', prefix: '+33' },
  { code: 'DE', name: 'Germany', prefix: '+49' },
  { code: 'GR', name: 'Greece', prefix: '+30' },
  { code: 'HU', name: 'Hungary', prefix: '+36' },
  { code: 'IS', name: 'Iceland', prefix: '+354' },
  { code: 'IE', name: 'Ireland', prefix: '+353' },
  { code: 'IT', name: 'Italy', prefix: '+39' },
  { code: 'XK', name: 'Kosovo', prefix: '+383' },
  { code: 'LV', name: 'Latvia', prefix: '+371' },
  { code: 'LI', name: 'Liechtenstein', prefix: '+423' },
  { code: 'LT', name: 'Lithuania', prefix: '+370' },
  { code: 'LU', name: 'Luxembourg', prefix: '+352' },
  { code: 'MT', name: 'Malta', prefix: '+356' },
  { code: 'MD', name: 'Moldova', prefix: '+373' },
  { code: 'MC', name: 'Monaco', prefix: '+377' },
  { code: 'ME', name: 'Montenegro', prefix: '+382' },
  { code: 'NL', name: 'Netherlands', prefix: '+31' },
  { code: 'MK', name: 'North Macedonia', prefix: '+389' },
  { code: 'NO', name: 'Norway', prefix: '+47' },
  { code: 'PL', name: 'Poland', prefix: '+48' },
  { code: 'PT', name: 'Portugal', prefix: '+351' },
  { code: 'RO', name: 'Romania', prefix: '+40' },
  { code: 'RU', name: 'Russia', prefix: '+7' },
  { code: 'SM', name: 'San Marino', prefix: '+378' },
  { code: 'RS', name: 'Serbia', prefix: '+381' },
  { code: 'SK', name: 'Slovakia', prefix: '+421' },
  { code: 'SI', name: 'Slovenia', prefix: '+386' },
  { code: 'ES', name: 'Spain', prefix: '+34' },
  { code: 'SE', name: 'Sweden', prefix: '+46' },
  { code: 'CH', name: 'Switzerland', prefix: '+41' },
  { code: 'UA', name: 'Ukraine', prefix: '+380' },
  { code: 'GB', name: 'United Kingdom', prefix: '+44' },
  { code: 'VA', name: 'Vatican City', prefix: '+379' },
  // Additional countries
  { code: 'US', name: 'United States', prefix: '+1' },
  { code: 'CA', name: 'Canada', prefix: '+1' },
  { code: 'AU', name: 'Australia', prefix: '+61' },
  { code: 'NZ', name: 'New Zealand', prefix: '+64' },
  { code: 'JP', name: 'Japan', prefix: '+81' },
  { code: 'KR', name: 'South Korea', prefix: '+82' },
  { code: 'CN', name: 'China', prefix: '+86' },
  { code: 'IN', name: 'India', prefix: '+91' },
  { code: 'BR', name: 'Brazil', prefix: '+55' },
  { code: 'AR', name: 'Argentina', prefix: '+54' },
  { code: 'MX', name: 'Mexico', prefix: '+52' },
  { code: 'ZA', name: 'South Africa', prefix: '+27' },
  { code: 'EG', name: 'Egypt', prefix: '+20' },
  { code: 'NG', name: 'Nigeria', prefix: '+234' },
  { code: 'KE', name: 'Kenya', prefix: '+254' },
  { code: 'MA', name: 'Morocco', prefix: '+212' },
  { code: 'TN', name: 'Tunisia', prefix: '+216' },
  { code: 'DZ', name: 'Algeria', prefix: '+213' },
  { code: 'LY', name: 'Libya', prefix: '+218' },
  { code: 'SD', name: 'Sudan', prefix: '+249' },
  { code: 'ET', name: 'Ethiopia', prefix: '+251' },
  { code: 'UG', name: 'Uganda', prefix: '+256' },
  { code: 'TZ', name: 'Tanzania', prefix: '+255' },
  { code: 'GH', name: 'Ghana', prefix: '+233' },
  { code: 'CI', name: 'Ivory Coast', prefix: '+225' },
  { code: 'SN', name: 'Senegal', prefix: '+221' },
  { code: 'ML', name: 'Mali', prefix: '+223' },
  { code: 'BF', name: 'Burkina Faso', prefix: '+226' },
  { code: 'NE', name: 'Niger', prefix: '+227' },
  { code: 'TD', name: 'Chad', prefix: '+235' },
  { code: 'CF', name: 'Central African Republic', prefix: '+236' },
  { code: 'CM', name: 'Cameroon', prefix: '+237' },
  { code: 'GQ', name: 'Equatorial Guinea', prefix: '+240' },
  { code: 'GA', name: 'Gabon', prefix: '+241' },
  { code: 'CG', name: 'Republic of the Congo', prefix: '+242' },
  { code: 'CD', name: 'Democratic Republic of the Congo', prefix: '+243' },
  { code: 'AO', name: 'Angola', prefix: '+244' },
  { code: 'GW', name: 'Guinea-Bissau', prefix: '+245' },
  { code: 'IO', name: 'British Indian Ocean Territory', prefix: '+246' },
  { code: 'AC', name: 'Ascension Island', prefix: '+247' },
  { code: 'SC', name: 'Seychelles', prefix: '+248' },
  { code: 'ST', name: 'São Tomé and Príncipe', prefix: '+239' },
  { code: 'CV', name: 'Cape Verde', prefix: '+238' },
  { code: 'GM', name: 'Gambia', prefix: '+220' },
  { code: 'GN', name: 'Guinea', prefix: '+224' },
  { code: 'SL', name: 'Sierra Leone', prefix: '+232' },
  { code: 'LR', name: 'Liberia', prefix: '+231' },
  { code: 'TG', name: 'Togo', prefix: '+228' },
  { code: 'BJ', name: 'Benin', prefix: '+229' },
  { code: 'MU', name: 'Mauritius', prefix: '+230' },
  { code: 'MG', name: 'Madagascar', prefix: '+261' },
  { code: 'ZW', name: 'Zimbabwe', prefix: '+263' },
  { code: 'NA', name: 'Namibia', prefix: '+264' },
  { code: 'MW', name: 'Malawi', prefix: '+265' },
  { code: 'LS', name: 'Lesotho', prefix: '+266' },
  { code: 'BW', name: 'Botswana', prefix: '+267' },
  { code: 'SZ', name: 'Eswatini', prefix: '+268' },
  { code: 'KM', name: 'Comoros', prefix: '+269' },
  { code: 'YT', name: 'Mayotte', prefix: '+262' },
  { code: 'RE', name: 'Réunion', prefix: '+262' },
  { code: 'DJ', name: 'Djibouti', prefix: '+253' },
  { code: 'SO', name: 'Somalia', prefix: '+252' },
  { code: 'ER', name: 'Eritrea', prefix: '+291' },
  { code: 'AW', name: 'Aruba', prefix: '+297' },
  { code: 'FO', name: 'Faroe Islands', prefix: '+298' },
  { code: 'GL', name: 'Greenland', prefix: '+299' },
  { code: 'GI', name: 'Gibraltar', prefix: '+350' },
  { code: 'PT', name: 'Portugal', prefix: '+351' },
  { code: 'LU', name: 'Luxembourg', prefix: '+352' },
  { code: 'IE', name: 'Ireland', prefix: '+353' },
  { code: 'IS', name: 'Iceland', prefix: '+354' },
  { code: 'AL', name: 'Albania', prefix: '+355' },
  { code: 'MT', name: 'Malta', prefix: '+356' },
  { code: 'CY', name: 'Cyprus', prefix: '+357' },
  { code: 'FI', name: 'Finland', prefix: '+358' },
  { code: 'BG', name: 'Bulgaria', prefix: '+359' },
  { code: 'LT', name: 'Lithuania', prefix: '+370' },
  { code: 'LV', name: 'Latvia', prefix: '+371' },
  { code: 'EE', name: 'Estonia', prefix: '+372' },
  { code: 'MD', name: 'Moldova', prefix: '+373' },
  { code: 'AM', name: 'Armenia', prefix: '+374' },
  { code: 'BY', name: 'Belarus', prefix: '+375' },
  { code: 'AD', name: 'Andorra', prefix: '+376' },
  { code: 'MC', name: 'Monaco', prefix: '+377' },
  { code: 'SM', name: 'San Marino', prefix: '+378' },
  { code: 'VA', name: 'Vatican City', prefix: '+379' },
  { code: 'UA', name: 'Ukraine', prefix: '+380' },
  { code: 'RS', name: 'Serbia', prefix: '+381' },
  { code: 'ME', name: 'Montenegro', prefix: '+382' },
  { code: 'XK', name: 'Kosovo', prefix: '+383' },
  { code: 'HR', name: 'Croatia', prefix: '+385' },
  { code: 'SI', name: 'Slovenia', prefix: '+386' },
  { code: 'BA', name: 'Bosnia and Herzegovina', prefix: '+387' },
  { code: 'MK', name: 'North Macedonia', prefix: '+389' },
  { code: 'IT', name: 'Italy', prefix: '+39' },
  { code: 'RO', name: 'Romania', prefix: '+40' },
  { code: 'CH', name: 'Switzerland', prefix: '+41' },
  { code: 'AT', name: 'Austria', prefix: '+43' },
  { code: 'GB', name: 'United Kingdom', prefix: '+44' },
  { code: 'DK', name: 'Denmark', prefix: '+45' },
  { code: 'SE', name: 'Sweden', prefix: '+46' },
  { code: 'NO', name: 'Norway', prefix: '+47' },
  { code: 'PL', name: 'Poland', prefix: '+48' },
  { code: 'DE', name: 'Germany', prefix: '+49' },
  { code: 'PE', name: 'Peru', prefix: '+51' },
  { code: 'MX', name: 'Mexico', prefix: '+52' },
  { code: 'CU', name: 'Cuba', prefix: '+53' },
  { code: 'AR', name: 'Argentina', prefix: '+54' },
  { code: 'BR', name: 'Brazil', prefix: '+55' },
  { code: 'CL', name: 'Chile', prefix: '+56' },
  { code: 'CO', name: 'Colombia', prefix: '+57' },
  { code: 'VE', name: 'Venezuela', prefix: '+58' },
  { code: 'MY', name: 'Malaysia', prefix: '+60' },
  { code: 'AU', name: 'Australia', prefix: '+61' },
  { code: 'ID', name: 'Indonesia', prefix: '+62' },
  { code: 'PH', name: 'Philippines', prefix: '+63' },
  { code: 'NZ', name: 'New Zealand', prefix: '+64' },
  { code: 'SG', name: 'Singapore', prefix: '+65' },
  { code: 'TH', name: 'Thailand', prefix: '+66' },
  { code: 'KZ', name: 'Kazakhstan', prefix: '+7' },
  { code: 'RU', name: 'Russia', prefix: '+7' },
  { code: 'JP', name: 'Japan', prefix: '+81' },
  { code: 'KR', name: 'South Korea', prefix: '+82' },
  { code: 'VN', name: 'Vietnam', prefix: '+84' },
  { code: 'CN', name: 'China', prefix: '+86' },
  { code: 'TR', name: 'Turkey', prefix: '+90' },
  { code: 'IN', name: 'India', prefix: '+91' },
  { code: 'PK', name: 'Pakistan', prefix: '+92' },
  { code: 'AF', name: 'Afghanistan', prefix: '+93' },
  { code: 'LK', name: 'Sri Lanka', prefix: '+94' },
  { code: 'MM', name: 'Myanmar', prefix: '+95' },
  { code: 'IR', name: 'Iran', prefix: '+98' },
  { code: 'SA', name: 'Saudi Arabia', prefix: '+966' },
  { code: 'AE', name: 'United Arab Emirates', prefix: '+971' },
  { code: 'IL', name: 'Israel', prefix: '+972' },
  { code: 'BH', name: 'Bahrain', prefix: '+973' },
  { code: 'QA', name: 'Qatar', prefix: '+974' },
  { code: 'BT', name: 'Bhutan', prefix: '+975' },
  { code: 'MN', name: 'Mongolia', prefix: '+976' },
  { code: 'NP', name: 'Nepal', prefix: '+977' },
  { code: 'TJ', name: 'Tajikistan', prefix: '+992' },
  { code: 'TM', name: 'Turkmenistan', prefix: '+993' },
  { code: 'AZ', name: 'Azerbaijan', prefix: '+994' },
  { code: 'GE', name: 'Georgia', prefix: '+995' },
  { code: 'KG', name: 'Kyrgyzstan', prefix: '+996' },
  { code: 'UZ', name: 'Uzbekistan', prefix: '+998' },
];

// Sort by country name for better UX
export const sortedCountryPrefixes = countryPrefixes.sort((a, b) => a.name.localeCompare(b.name));

// Find country by prefix
export const findCountryByPrefix = (prefix: string): CountryPrefix | undefined => {
  return countryPrefixes.find(country => country.prefix === prefix);
};

// Find country by code
export const findCountryByCode = (code: string): CountryPrefix | undefined => {
  return countryPrefixes.find(country => country.code === code);
}; 